name: Update README with LeetCode Stats

on:
  push:
    paths:
      - "stats.json"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read stats.json
        id: stats
        run: |
          solved=$(jq '.leetcode.solved' stats.json)
          easy=$(jq '.leetcode.easy' stats.json)
          medium=$(jq '.leetcode.medium' stats.json)
          hard=$(jq '.leetcode.hard' stats.json)
          echo "solved=$solved" >> $GITHUB_OUTPUT
          echo "easy=$easy" >> $GITHUB_OUTPUT
          echo "medium=$medium" >> $GITHUB_OUTPUT
          echo "hard=$hard" >> $GITHUB_OUTPUT

      - name: Update README.md
        run: |
          chart_url="https://quickchart.io/chart?c={type:'pie',data:{labels:['Solved','Easy','Medium','Hard'],datasets:[{data:[${{ steps.stats.outputs.solved }},${{ steps.stats.outputs.easy }},${{ steps.stats.outputs.medium }},${{ steps.stats.outputs.hard }}]}]}}"
          sed -i "s|!\[LeetCode Stats\](.*)|![LeetCode Stats]($chart_url)|" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update LeetCode stats chart"
          git push
