name: Update README with LeetCode Stats

on:
  push:
    paths:
      - stats.json
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update stats in README
        run: |
          TOTAL=$(jq '.leetcode.solved' stats.json)
          EASY=$(jq '.leetcode.easy' stats.json)
          MEDIUM=$(jq '.leetcode.medium' stats.json)
          HARD=$(jq '.leetcode.hard' stats.json)

          # Build stats block
          STATS="Total Solved: $TOTAL\nEasy: $EASY | Medium: $MEDIUM | Hard: $HARD"

          # Replace or append block in README
          if grep -q "Total Solved:" README.md; then
            # Replace both lines (Total Solved + difficulty line)
            sed -i "/Total Solved:/c\\Total Solved: $TOTAL" README.md
            if grep -q "Easy:" README.md; then
              sed -i "/Easy:/c\\Easy: $EASY | Medium: $MEDIUM | Hard: $HARD" README.md
            else
              sed -i "/Total Solved:/a Easy: $EASY | Medium: $MEDIUM | Hard: $HARD" README.md
            fi
          else
            echo -e "$STATS" >> README.md
          fi

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
